StorePanel.Web/Areas/Dashboard/Controllers/RolesController.cs
using DataTablesParser;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Newtonsoft.Json;
using StorePanel.Core.Models;
using StorePanel.Web.Areas.Dashboard.ViewModels;
using StorePanel.Web.Helpers;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace StorePanel.Web.Areas.Dashboard.Controllers
{
    [Area("Dashboard")]
    [Authorize("Permission")]
    public class RolesController : Controller
    {
        private readonly UserManager<User> _userManager;
        private readonly RoleManager<IdentityRole> _roleManager;
        private readonly IRolePermissionService _rolePermissionService;
        private readonly ILogger<RolesController> _logger;

        public RolesController(
                UserManager<User> userManager,
                RoleManager<IdentityRole> roleManager,
                IRolePermissionService rolePermissionService,
                ILogger<RolesController> logger)
        {
            _userManager = userManager;
            _roleManager = roleManager;
            _rolePermissionService = rolePermissionService;
            _logger = logger;
        }

        public IActionResult Index(bool root = false)
        {
            ViewBag.Root = root;
            return View();
        }
        [HttpPost]
        [AllowAnonymous]
        public string LoadGrid()
        {
            var roles = _roleManager.Roles.Select(item =>
                            new RoleViewModel()
                            {
                                Id = item.Id,
                                Name = item.Name,
                            }
                            );
            var parser = new Parser<RoleViewModel>(Request.Form, roles);
            return JsonConvert.SerializeObject(parser.Parse());
        }
        public IActionResult Create()
        {
            return PartialView(new RoleViewModel());
        }

        [HttpPost]
        public async Task<IActionResult> Create(RoleViewModel viewModel)
        {
            if (ModelState.IsValid)
            {
                var result = await _roleManager.CreateAsync(new IdentityRole() { Name = viewModel.Name });
                if (result.Succeeded)
                {
                    return RedirectToAction(nameof(Index));
                }
                else
                {
                    ModelState.AddModelError("Name", string.Join(",", result.Errors));
                }
            }

            return View(viewModel);
        }
        public async Task<IActionResult> Edit(string id)
        {
            var role = await _roleManager.FindByIdAsync(id);
            var vm = new RoleViewModel
            {
                Id = role.Id,
                Name = role.Name
            };
            return PartialView(vm);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(RoleViewModel vm)
        {
            if (ModelState.IsValid)
            {
                var role = await _roleManager.FindByIdAsync(vm.Id);
                role.Name = vm.Name;
                var result = await _roleManager.UpdateAsync(role);
                if (result.Succeeded)
                {
                    return RedirectToAction(nameof(Index));
                }
                else
                {
                    ModelState.AddModelError("Name", string.Join(",", result.Errors));
                }
            }

            return View(vm);
        }
        public async Task<IActionResult> Delete(string id)
        {
            var role = await _roleManager.FindByIdAsync(id);
            return PartialView(role);
        }
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            var role = await _roleManager.FindByIdAsync(id);
            var result = await _roleManager.DeleteAsync(role);

            return RedirectToAction(nameof(Index));
        }
        public async Task<IActionResult> EditRolePermission(string id)
        {
            var permissions = new List<NavigationMenuViewModel>();
            if (!string.IsNullOrWhiteSpace(id))
            {
                permissions = await _rolePermissionService.GetPermissionsByRoleIdAsync(id);
            }
            var role = await _roleManager.FindByIdAsync(id);
            ViewBag.RoleName = role.Name;
            ViewBag.RoleId = id;
            return View(permissions);
        }

        [HttpPost]
        public async Task<IActionResult> EditRolePermission(string id, string selectedPermissions)
        {
            if (ModelState.IsValid)
            {
                var permissionIds = new List<int>();
                if (selectedPermissions != null && string.IsNullOrEmpty(selectedPermissions) == false)
                {
                    var selectedPermisisonsArr = selectedPermissions.Split(',');
                    permissionIds = selectedPermisisonsArr.Select(x => Convert.ToInt32(x)).ToList();
                }
                await _rolePermissionService.SetPermissionsByRoleIdAsync(id, permissionIds);
                return RedirectToAction(nameof(Index));
            }
            var role = await _roleManager.FindByIdAsync(id);
            ViewBag.RoleName = role.Name;
            ViewBag.RoleId = id;
            return View(selectedPermissions);
        }
    }
}

StorePanel.Web/Areas/Dashboard/Views/Roles/Delete.cshtml
@model Microsoft.AspNetCore.Identity.IdentityRole
<input type="hidden" id="title" value="حذف نقش" />

<h4 class="card-label">
    آیا مطمئن هستید که می خواهید این رکورد را حذف کنید؟
</h4>
<dl class="row" style="padding-top:10px">
    <dt class="col-sm-4">
        نام
    </dt>
    <dd class="col-sm-8">
        @Html.DisplayFor(model => model.Name)
    </dd>
</dl>
<div style="float:left">
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()
        <input type="submit" value="حذف" class="btn btn-danger mr-2" />
    }
</div>

StorePanel.Web/Areas/Dashboard/Views/Roles/Edit.cshtml
@model RoleViewModel

<input type="hidden" id="title" value="ویرایش نقش" />

<form asp-action="Edit" method="post" id="form">
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <input type="hidden" asp-for="Id" />
    <div class="form-group">
        <label asp-for="Name" class="control-label col-md-2">نام</label>
        <div class="col-md-10">
            <input asp-for="Name" class="form-control" required />
            <span asp-validation-for="Name" class="text-danger"></span>
        </div>
    </div>
    <div class="form-group">
        <div style="float:left">
            <input type="submit" value="ثبت" class="btn btn-primary mr-2" />
        </div>
    </div>
</form>
<script>
    $.validator.unobtrusive.parse("#form");
</script>

StorePanel.Web/Areas/Dashboard/Views/Roles/EditRolePermission.cshtml
@model List<NavigationMenuViewModel>
@{
    ViewData["Title"] = "ویرایش دسترسی ها";
}
<input type="hidden" id="nav_active" value="auth_control">
<input type="hidden" id="nav_item_active" value="roles">
@using StorePanel.Web.Helpers
@section Header {
    <link href="~/admin/vendors/jstree/jstree.bundle.css" rel="stylesheet" />
}
<div class="col-lg-6">
    <div class="card card-custom gutter-b">
        <div class="card-header">
            <h3 class="card-title">
                دسترسی نقش : @ViewBag.RoleName
            </h3>
        </div>
        <form method="post" id="form">
            <div style="padding:20px">
                <div id="jstree" class="tree-demo">
                    <ul>
                        @foreach (var item in Model.Where(m => m.ParentMenuId == null))
                        {
                            <li data-jstree='{"opened": true, "selected" : @(item.Permitted.ToString().ToLower()) }' id="@item.Id">
                                @item.Name
                                @if (Model.Any(m => m.ParentMenuId == item.Id))
                                {
                                    <ul>
                                        @foreach (var child in Model.Where(m => m.ParentMenuId == item.Id))
                                        {

                                            var data = RecursiveMethods.GetPermissionsTree(Model.Where(m => m.ParentMenuId != null).ToList(), child);
                                            @Html.Raw(data);
                                        }
                                    </ul>
                                }
                            </li>
                        }
                    </ul>
                </div>
            </div>
            <br />
            <div class="card-footer">
                    <div class="form-footer">
                        <a href="@Url.Action("Index")" class="btn-cancel ml-2">انصراف</a> |
                        <input type="submit" value="ذخیره تغییرات" class="btn btn-primary btn-rounded mr-2" />
                    </div>
            </div>
        </form>
    </div>
</div>
@section Scripts {
    <script src="~/admin/vendors/jstree/jstree.bundle.js"></script>
    <script>
       var tree = $("#jstree").jstree({
            "plugins": ["checkbox", "types"],
            "core": {
                "themes": {
                    "responsive": false
                }
           },
           "checkbox": {
               "three_state": false,
           },
           "types": {
               "default": {
                   "icon": "fa fa-folder text-warning"
               },
               "file": {
                   "icon": "fa fa-file  text-warning"
               }
           },
       });
        $("#form").submit(function (event) {
            event.preventDefault();
            var selectedElmsIds = [];
            var selectedElms = $('#jstree').jstree("get_selected", true);
            $.each(selectedElms, function () {
                selectedElmsIds.push(this.id);
            });

            //// Mark undetermined as selected
            //var indeterminedElms = $('#jstree').jstree("get_undetermined", true);
            //$.each(indeterminedElms, function () {
            //    selectedElmsIds.push(this.id);
            //});
            console.log(selectedElmsIds);
            var selectedStr = "";
            if (selectedElmsIds.length > 0) {
                selectedStr = selectedElmsIds.join();
            }
            $.post("/Admin/Roles/EditRolePermission/@ViewBag.RoleID?selectedPermissions=" + selectedStr,
                function (result) {
                    location.href = "@Url.Action("Index","Roles")";
                });
        });
    </script>
}

StorePanel.Web/Areas/Dashboard/Views/Roles/Index.cshtml
@{
    ViewData["Title"] = "کاربران";
}
<input type="hidden" id="nav_active" value="article_control">
<input type="hidden" id="nav_item_active" value="articles">

<div class="page-header">
    <div>
        <h3>@ViewData["Title"]</h3>
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a asp-area="Dashboard" asp-controller="Home" asp-action="Index">داشبورد</a></li>
                <li class="breadcrumb-item active" aria-current="page"><a href="javascript:void(0)">@ViewData["Title"]</a></li>
            </ol>
        </nav>
    </div>
    <validate-permission asp-controller="Roles" asp-action="Create">
            <a onclick="openModal('/Dashboard/Roles/Create')" class="btn btn-success text-white font-weight-bolder">
                رکورد جدید
            </a>
    </validate-permission>
</div>
<div class="card">
    <div class="card-body table-responsive">
        <table id="datatable" class="table table-striped table-bordered">
            <thead>
                <tr>
                    <th>Id</th>
                    <th>نام</th>
                    <th>دستورات</th>
                </tr>
            </thead>
        </table>
    </div>
</div>
@section Scripts {
    <script>
        $(function () {
            @if (ViewBag.Root != null && ViewBag.Root != false)
            {
                <text>
                    localStorage.removeItem('DataTables_datatable_' + window.location.pathname);
                </text>
            }
            var table = $('#datatable').DataTable({
                ajax: {
                    url: '/Dashboard/Roles/LoadGrid',
                    type: "POST"
                },
                stateSave: true,
                order: [0,"desc"], // descending order with first column witch is hidden id
                columnDefs: [
                    {
                        "targets": [0],
                        "visible": false,
                        "searchable": false
                    }
                ],
                columns: [
                    { data: "Id" },
                    { data: "Name" },
                    {
                        data: "Id",
                        responsivePriority: -1,
                        render: function (data, type, row) {
                            var content = "";
                            @{
                                if (await PermissionHelper.UserHasPermission("Roles", "Edit"))
                                {
                                    <text>
                                        if(row.Id !== "@DefaultValues.ADMIN_ROLE_ID" && row.Id !== "@DefaultValues.SUPER_USER_ROLE_ID"){
                                            var element = `\
                                        <a class='btn btn-sm btn-clean btn-icon mr-2' onclick="openModal('/Dashboard/Roles/Edit/${row.Id}')">\
                                        <i class='far fa-edit text-primary'></i>\
                                        </a>\
                                        `;
                                            content += element;
                                        }
                                    </text>
                                }
                                if (await PermissionHelper.UserHasPermission("Roles", "Delete"))
                                {
                                    <text>
                                        if(row.Id !== "@DefaultValues.ADMIN_ROLE_ID" && row.Id !== "@DefaultValues.SUPER_USER_ROLE_ID"){
                                            var element = `\
                                        <a class='btn btn-sm btn-clean btn-icon' onclick="openModal('/Dashboard/Roles/Delete/${row.Id}')">\
                                        <i class='far fa-trash-alt text-danger'></i>\
                                        </a>\
                                        `;
                                            content += element;
                                        }
                                    </text>
                                }
                                if (await PermissionHelper.UserHasPermission("Roles", "EditRolePermission"))
                                {
                                    <text>
                                        if(row.Id !== "@DefaultValues.SUPER_USER_ROLE_ID"){
                                            var element = `<a class='btn btn-light btn-sm ml-2' href='/Dashboard/Roles/EditRolePermission/${row.Id}'>دسترسی</a>`;
                                            content += element;
                                }
                                    </text>
                                }
                             }
                            return content;
                        },
                        width:"200px",
                        orderable: false
                    },

                ],
            });
        });
    </script>
}