StorePanel.Web/Controllers/ContactUsController.cs
using Microsoft.AspNetCore.Mvc;
using StorePanel.Core.Models;
using StorePanel.Infrastructure.Repository;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace StorePanel.Web.Controllers
{
    public class ContactUsController : Controller
    {
        private readonly IContactUsFormRepository _contactUsFormRepository;

        private readonly IStaticContentRepository _staticContentRepository;

        public ContactUsController(IContactUsFormRepository contactUsFormRepository
        ,IStaticContentRepository staticContentRepository)
        {
            _contactUsFormRepository = contactUsFormRepository;

            _staticContentRepository = staticContentRepository;
        }

        public async Task<IActionResult> Index(bool Saved=false)
        {
            ViewBag.Saved = Saved;
            return View(await _staticContentRepository.GetById(1));
        }

        [HttpPost]
        public async Task<IActionResult> Index(ContactForm model)
        {
            if (ModelState.IsValid)
            {
                await _contactUsFormRepository.Add(model);
            }

            return RedirectToAction("Index",new { Saved=true});
        }

        public async Task<IActionResult> News(ContactForm contactForm)
        {
            contactForm.Message = "عضویت خبرنامه";
            contactForm.Phone = "-";
            contactForm.Name = "-";
            await _contactUsFormRepository.Add(contactForm);

            return RedirectToAction("Index","Home");
        }
        public IActionResult Subscribe()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Subscribe(ContactForm model)
        {

            if (ModelState.IsValid)
            {
                _contactUsFormRepository.Add(model);
            }

            return PartialView(model);
        }
    }
}

StorePanel.Web/Views/ContactUs/Index.cshtml
@{
    ViewData["Title"] = "تماس با ما";
}


@model StorePanel.Core.Models.StaticContent

<main class="main">
    <div class="page-header text-center" style="background-image: url('assets/images/page-header-bg.jpg')">
        <div class="container">
            <h1 class="page-title">تماس با ما</h1>
        </div><!-- End .container -->
    </div><!-- End .page-header -->
    <nav aria-label="breadcrumb" class="breadcrumb-nav border-0 mb-0">
        <div class="container">
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="/">خانه</a></li>
                <li class="breadcrumb-item active" aria-current="page">تماس با ما </li>
            </ol>
        </div><!-- End .container -->
    </nav><!-- End .breadcrumb-nav -->

    <div class="page-content">
        <div class="col-12 d-flex mb-5">
            <div class="bg-white w-100 mapincontact">
                @Html.Raw(Model.Map)
            </div>
        </div>
        <div class="container">
            <div class="row">
                <div class="col-md-4">
                    <div class="contact-box text-center">
                        <h3>دفتر</h3>

                        <address>@Model.Address</address>
                    </div><!-- End .contact-box -->
                </div><!-- End .col-md-4 -->

                <div class="col-md-4">
                    <div class="contact-box text-center">
                        <h3>اطلاعات تماس</h3>

                        <div><a href="mailto:@Model.Email">@Model.Email</a></div>
                        <div><a href="tel:@Model.Phone">@Model.Phone</a>,<a href="tel:@Model.Mobile">@Model.Mobile</a></div>
                    </div><!-- End .contact-box -->
                </div><!-- End .col-md-4 -->

                <div class="col-md-4">
                    <div class="contact-box text-center">
                        <h3>شبکه های اجتماعی</h3>

                        <div class="social-icons social-icons-color justify-content-center">
                            <a href="https://@Model.Twitter" class="social-icon social-twitter" title="توییتر" target="_blank">
                                <i class="icon-twitter"></i>
                            </a>
                            <a href="https://@Model.Instagram" class="social-icon social-instagram" title="اینستاگرام"
                               target="_blank"><i class="icon-instagram"></i></a>
                            <a href="https://@Model.WhatsApp" class="social-icon social-youtube" title="واتس اپ" target="_blank">
                                <i class="icon-youtube"></i>
                            </a>
                            <a href="https://@Model.Telegram" class="social-icon social-pinterest" title="تلگرام" target="_blank">
                                <i class="icon-pinterest"></i>
                            </a>
                        </div><!-- End .soial-icons -->
                    </div><!-- End .contact-box -->
                </div><!-- End .col-md-4 -->
            </div><!-- End .row -->

            <hr class="mt-3 mb-5 mt-md-1">
            <div class="touch-container row justify-content-center">
                <div class="col-md-9 col-lg-7">
                    <div class="text-center">
                        <h2 class="title mb-1 text-center">تماس با ما</h2><!-- End .title mb-2 -->
                        <p class="lead text-primary text-center mb-5">
                            از طریق فرم زیر میتوانید با ما ارتباط برقرار کنید
                        </p><!-- End .lead text-primary -->

                        <form asp-action="Index" asp-controller="ContactUs" class="contact-form mb-2">
                            @if (ViewBag.Saved == true)
                            {
                                <p class="bg-success text-white text-center p-1 mb-1">ثبت شد</p>
                            }

                            <div class="row">
                                <div class="col-sm-4">
                                    <label for="cname" class="sr-only">نام</label>
                                    <input type="text" class="form-control" id="cname" name="Name"
                                           placeholder="نام خود را وارد کنید *" required>
                                </div>

                                <div class="col-sm-4">
                                    <label for="cemail" class="sr-only">ایمیل</label>
                                    <input type="email" class="form-control" id="cemail" asp-for="Email"
                                           placeholder="ایمیل خود را وارد کنید *" required>
                                </div><!-- End .col-sm-4 -->

                                <div class="col-sm-4">
                                    <label for="cphone" class="sr-only">شماره موبایل</label>
                                    <input type="tel" class="form-control" id="cphone" asp-for="Phone"
                                           placeholder="شماره موبایل خود را وارد کنید">
                                </div><!-- End .col-sm-4 -->
                            </div><!-- End .row -->

                            <label for="cmessage" class="sr-only">پیام</label>
                            <textarea class="form-control" cols="30" rows="4" id="cmessage" required name="Message"
                                      placeholder="متن پیام شما *"></textarea>

                            <div class="text-center">
                                <button type="submit" class="btn btn-outline-primary-2 btn-minwidth-sm">
                                    <span>تایید و ارسال</span>
                                    <i class="icon-long-arrow-left"></i>
                                </button>
                            </div>
                        </form>
                    </div><!-- End .col-md-9 col-lg-7 -->
                </div><!-- End .row -->
            </div><!-- End .container -->
        </div><!-- End .page-content -->
</main><!-- End .main -->

StorePanel.Web/Views/ContactUs/Subscribe.cshtml
@model StorePanel.Core.Models.StaticContent


<div class="footer-newsletter bg-image"
     style="background-image: url(/assets/Newimage/widedimageforbottom.jpg)">
    <div class="container">
        <div class="heading text-center">
            <h3 class="title text-center">عضویت در خبرنامه</h3><!-- End .title -->
            <!-- End .title-desc -->
        </div><!-- End .heading -->

        <div class="row">
            <div class="col-sm-10 offset-sm-1 col-md-8 offset-md-2 col-lg-6 offset-lg-3">
                <form asp-action="Subscribe" asp-controller="ContactUs">
                    <div class="input-group">
                        <input type="email" asp-for="Email" class="form-control" placeholder="آدرس ایمیل خود را وارد کنید"
                               aria-label="Email Adress" aria-describedby="newsletter-btn" required>
                        <div class="input-group-append">
                            <button class="btn btn-primary" type="submit"
                                    id="newsletter-btn">
                                <span>عضویت</span><i class="icon-long-arrow-left"></i>
                            </button>
                        </div><!-- .End .input-group-append -->
                    </div><!-- .End .input-group -->
                </form>
            </div><!-- End .col-sm-10 offset-sm-1 col-lg-6 offset-lg-3 -->
        </div><!-- End .row -->
    </div><!-- End .container -->
</div><!-- End .footer-newsletter bg-image -->