StorePanel.Web/Areas/Dashboard/Controllers/HomeController.cs
using ImageMagick;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using StorePanel.Core.Models;
using StorePanel.Infrastructure.Repository;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;

namespace StorePanel.Web.Areas.Dashboard.Controllers
{
    [Area("Dashboard")]
    [Route("Dashboard")]
    [Authorize]
    public class HomeController : Controller
    {
        private readonly ITagRepository _tagRepo;

        private UserManager<User> _userManager;

        public HomeController(ITagRepository tagRepo,UserManager<User> userManager)
        {
            _tagRepo = tagRepo;

            _userManager = userManager;
        }

        public async Task<IActionResult> Index()
        {

            var currentUser = await _userManager.FindByNameAsync(User.Identity.Name);
            if (currentUser == null)
            {
                return NotFound();
            }
            ViewBag.Avatar = currentUser.Avatar;
            return View();
        }

        [AllowAnonymous]
        [Route("Home/GetTags")]
        public JsonResult GetTags(string searchStr)
        {
            var suggestion = new List<string>();
            if (string.IsNullOrEmpty(searchStr) == false)
            {
                suggestion = _tagRepo.GetDefaultQuery().Where(
                    p => p.Title.ToLower().Trim().Contains(searchStr.ToLower().Trim())
                ).Select(p => p.Title).ToList();
            }
            return Json(suggestion);
        }
        [AllowAnonymous]
        [Route("Home/UploadImage")]
        public async Task<string> UploadImage(IFormFile file, bool? hasWatermark)
        {
            var fileName = Guid.NewGuid() + ".webp";
            var tempUploadFolder = Path.Combine(Directory.GetCurrentDirectory(), "UploadedFiles", "Temp");
            var tempUploadFilePath = Path.Combine(tempUploadFolder, fileName);

            await using (var fileStream = new FileStream(tempUploadFilePath, FileMode.Create))
            {
                await file.CopyToAsync(fileStream);

                var uploadFolder = Path.Combine(Directory.GetCurrentDirectory(), "UploadedFiles", "Images");
                var uploadFilePath = Path.Combine(uploadFolder, fileName);
                var waterMark = Path.Combine(Path.Combine(Directory.GetCurrentDirectory(), "wwwroot"), "light-logo.png");
                using (MagickImage image = new MagickImage(tempUploadFilePath))
                {
                    if (hasWatermark != null && hasWatermark == true)
                    {
                        using (var watermark = new MagickImage(waterMark))
                        {

                            watermark.Evaluate(Channels.Alpha, EvaluateOperator.Divide, 4);
                            image.Composite(watermark, Gravity.Southeast, CompositeOperator.Over);

                        }
                    }
                    image.Format = MagickFormat.WebP;
                    image.Quality = 75;
                    image.Write(uploadFilePath);
                }

                var lowQualityFolder = Path.Combine(Directory.GetCurrentDirectory(), "UploadedFiles", "LowImage");
                var lowQualityFilePath = Path.Combine(lowQualityFolder, fileName);
                using (MagickImage image = new MagickImage(tempUploadFilePath))
                {
                    image.Blur(0, 10);
                    image.Format = MagickFormat.WebP;
                    image.Quality = 10;
                    image.Write(lowQualityFilePath);
                }
            }
            if (System.IO.File.Exists(tempUploadFilePath))
            {
                try
                {
                    System.IO.File.Delete(tempUploadFilePath);
                }
                catch (Exception ex)
                {
                    //Do something
                }
            }
            return fileName;
        }
    }
}

StorePanel.Web/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using StorePanel.Infrastructure.Repository;
using StorePanel.Web.Models;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace StorePanel.Web.Controllers
{
    public class HomeController : Controller
    {
        private readonly IStaticContentRepository _staticContentRepository;



        public HomeController(IStaticContentRepository staticContentRepository)
        {
            _staticContentRepository = staticContentRepository;
        }
        public IActionResult Index()
        {
            return View();
        }

        [Route("Aboutus")]
        public async Task<IActionResult> Aboutus()
        {
            var model = _staticContentRepository.GetAll().Result[0];
            return View(model);
        }
    }
}

StorePanel.Web/ViewComponents/BrandsViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using StorePanel.Infrastructure.Repository;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace StorePanel.Web.ViewComponents
{
    public class BrandsViewComponent :ViewComponent
    {
        private readonly IBrandsRepository _brandsRepository;

        public BrandsViewComponent(IBrandsRepository brandsRepository)
        {
            _brandsRepository = brandsRepository;
        }

        public async Task<IViewComponentResult> InvokeAsync()
        {
            return View(await _brandsRepository.GetAll());
        }
    }
}

StorePanel.Web/ViewComponents/SliderViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using StorePanel.Infrastructure.Repository;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace StorePanel.Web.ViewComponents
{
    public class SliderViewComponent :ViewComponent
    {
        private readonly ISliderRepository _sliderRepository;

        public SliderViewComponent(ISliderRepository sliderRepository)
        {
            _sliderRepository = sliderRepository;
        }

        public async Task<IViewComponentResult> InvokeAsync()
        {
            return View(await _sliderRepository.GetAll());
        }
    }
}

StorePanel.Web/ViewComponents/TopSoldViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using StorePanel.Infrastructure.Repository;
using StorePanel.Infrastructure.Service;
using StorePanel.Web.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace StorePanel.Web.ViewComponents
{
    public class TopSoldViewComponent : ViewComponent 
    {
        private readonly IInvoicesRepository _invoicesRepository;
        private readonly IProductService _productService;

        public TopSoldViewComponent(IInvoicesRepository invoicesRepository, IProductService productService)
        {
            _invoicesRepository = invoicesRepository;
            _productService = productService;
        }

        public IViewComponentResult Invoke()
        {
            var products = _productService.GetTopSoldProductsWithPrice(8).Result;
            var vm = new List<ProductWithPriceViewModel>();
            foreach (var product in products)
                vm.Add(new ProductWithPriceViewModel(product));
            return View(vm);
        }
    }
}

StorePanel.Web/Views/Home/Aboutus.cshtml
@model StorePanel.Core.Models.StaticContent

@{
    ViewData["Title"] = "درباره ما";
}


<main class="main">
    <div class="page-header text-center" style="background-image: url('/assets/images/page-header-bg.jpg')">
        <div class="container">
            <h1 class="page-title">درباره ما<span></span></h1>
        </div><!-- End .container -->
    </div><!-- End .page-header -->
    <nav aria-label="breadcrumb" class="breadcrumb-nav">
        <div class="container">
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="/">خانه</a></li>
                <li class="breadcrumb-item active" aria-current="page">درباره ما</li>
            </ol>
        </div><!-- End .container -->
    </nav><!-- End .breadcrumb-nav -->

    <div class="page-content pb-3">
        <div class="container">
            <div class="row">
                <div class="col-lg-10 offset-lg-1">
                    <div class="about-text text-center mt-3">
                        <h2 class="title text-center mb-2">
                            @Model.AboutUsTitle
                        </h2><!-- End .title text-center mb-2 -->
                        <p class="text-center">
                            @Model.AboutUsDescription
                        </p>

                    </div><!-- End .about-text -->
                </div><!-- End .col-lg-10 offset-1 -->
            </div><!-- End .row -->
        </div><!-- End .container -->

        <div class="mb-2"></div><!-- End .mb-2 -->

        <div class="bg-image pt-7 pb-5 pt-md-12 pb-md-9"
             style="background-image: url(/assets/images/backgrounds/bg-4.jpg);background-position-y:bottom;">
            <div class="container">
                <div class="row">
                    <div class="col-6 col-md-3">
                        <div class="count-container text-center">
                            <div class="count-wrapper text-white">
                                <span class="count" data-from="0" data-to="@Model.Counter1Num" data-speed="3000"
                                      data-refresh-interval="50">0</span>
                            </div><!-- End .count-wrapper -->
                            <h3 class="count-title text-white">
                                @Model.Counter1Title
                            </h3><!-- End .count-title -->
                        </div><!-- End .count-container -->
                    </div><!-- End .col-6 col-md-3 -->

                    <div class="col-6 col-md-3">
                        <div class="count-container text-center">
                            <div class="count-wrapper text-white">
                                <span class="count" data-from="0" data-to="@Model.Counter2Num" data-speed="3000"
                                      data-refresh-interval="50">0</span>
                            </div><!-- End .count-wrapper -->
                            <h3 class="count-title text-white">
                                @Model.Counter2Title
                            </h3><!-- End .count-title -->
                        </div><!-- End .count-container -->
                    </div><!-- End .col-6 col-md-3 -->

                    <div class="col-6 col-md-3">
                        <div class="count-container text-center">
                            <div class="count-wrapper text-white">
                                <span class="count" data-from="0" data-to="@Model.Counter3Num" data-speed="3000"
                                      data-refresh-interval="50">0</span>
                            </div><!-- End .count-wrapper -->
                            <h3 class="count-title text-white">
                                @Model.Counter3Title
                            </h3><!-- End .count-title -->
                        </div><!-- End .count-container -->
                    </div><!-- End .col-6 col-md-3 -->

                    <div class="col-6 col-md-3">
                        <div class="count-container text-center">
                            <div class="count-wrapper text-white">
                                <span class="count" data-from="0" data-to="@Model.Counter4Num" data-speed="3000"
                                      data-refresh-interval="50">0</span>
                            </div><!-- End .count-wrapper -->
                            <h3 class="count-title text-white">
                                @Model.Counter4Title
                            </h3><!-- End .count-title -->
                        </div><!-- End .count-container -->
                    </div><!-- End .col-6 col-md-3 -->
                </div><!-- End .row -->
            </div><!-- End .container -->
        </div><!-- End .bg-image pt-8 pb-8 -->

        @await Component.InvokeAsync("BrandsAboutus")

    </div><!-- End .page-content -->
</main><!-- End .main -->

StorePanel.Web/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "خانه";
}

<main class="main">
    @await Component.InvokeAsync("Slider")

    @await Component.InvokeAsync("Brands")

    <div class="mb-3 mb-lg-5"></div><!-- End .mb-3 mb-lg-5 -->

    <div class="mb-3"></div><!-- End .mb-6 -->

    <div class="container">
        <ul class="nav nav-pills nav-border-anim nav-big justify-content-center mb-3" role="tablist">
            <li class="nav-item">
                <a class="nav-link active" id="products-featured-link" data-toggle="tab"
                   href="#products-featured-tab" role="tab" aria-controls="products-featured-tab"
                   aria-selected="true">
                    تخفیف دار
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" id="products-sale-link" data-toggle="tab" href="#products-sale-tab"
                   role="tab" aria-controls="products-sale-tab" aria-selected="false">بیشترین فروش</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" id="products-top-link" data-toggle="tab" href="#products-top-tab" role="tab"
                   aria-controls="products-top-tab" aria-selected="false">بیشترین امتیاز</a>
            </li>
        </ul>
    </div><!-- End .container -->

    <div class="container-fluid">
        <div class="tab-content tab-content-carousel">
            @await Component.InvokeAsync("ProductWithOffer")
            @await Component.InvokeAsync("TopSold")
            @await Component.InvokeAsync("HighestRateProducts")
        </div><!-- End .tab-content -->
    </div><!-- End .container-fluid -->



    <div class="mb-6"></div><!-- End .mb-6 -->

    <div class="container">
        <div class="heading heading-center mb-3">
            <h2 class="title text-center">محصولات اخیر</h2><!-- End .title -->
            @await Component.InvokeAsync("NewestProduct")

        </div><!-- End .container -->
    </div>
    <div class="container">
        <hr class="mt-1 mb-6">
    </div><!-- End .container -->

    @await Component.InvokeAsync("RecentArtilcel_Index")

</main><!-- End .main -->